export const ALL_LICENCE_TYPES = [
  'FI', 'FE', 'ATC FI', 'ATC FE',
  'PPL', 'CPL', 'ATPL',
  'IR ME',
  'Qualification Type',
  'Multi Crew attestation',
  'CAT 1', 'CAT 2', 'CAT 3', 'CAT 4', 'CAT 5', 'CAT 6',
  'C1', 'C2', 'C3', 'C4', 'C6',
  'CLASS-M', 'CLASS-MT', 'CLASS-MRP',
  'IFR', 'VFR',
  'COM 1', 'COM 2', 'COM 3', 'COM 4', 'COM 5', 'COM 6',
  'CAL-ATC', 'CAL-AFIS',
  'PCAL-ATC', 'PCAL-AFIS',
  'LPAFIS', 'LATC',
] as const;
