-- ============================================
-- AeroSchool — table aeroschool_question_modules
-- Ajout de 50 QCM « formation théorique » (instructeurs / examinateurs / ATC).
-- CONSERVE les questions déjà présentes : jsonb || concatène les tableaux.
-- ============================================

UPDATE aeroschool_question_modules
SET
  -- Ancien contenu de questions en premier, puis les 50 nouvelles entrées
  questions = COALESCE(questions, '[]'::jsonb) || $qcm$[
    {"id":"aeroschool-theo-001","title":"Lors de l'obtention de l'ATIS, quelle information est prioritaire pour régler l'altimètre ?","options":["A) La température extérieure","B) Le QNH","C) La visibilité","D) Le vent en surface"],"correct_answers":["B) Le QNH"]},
    {"id":"aeroschool-theo-002","title":"Quelle est la vitesse maximale de roulage en ligne droite ?","options":["A) 15 kts","B) 20 kts","C) 30 kts","D) 40 kts"],"correct_answers":["C) 30 kts"]},
    {"id":"aeroschool-theo-003","title":"Lors d'un virage en roulage, quelle vitesse ne doit pas être dépassée ?","options":["A) 10 kts","B) 15 kts","C) 20 kts","D) 30 kts"],"correct_answers":["A) 10 kts"]},
    {"id":"aeroschool-theo-004","title":"Avant le décollage, où les checklists Before Takeoff doivent-elles être complétées ?","options":["A) En début de piste après alignement","B) Pendant le roulage vers la piste","C) Au point d'attente","D) Après avoir reçu la clairance de décollage"],"correct_answers":["C) Au point d'attente"]},
    {"id":"aeroschool-theo-005","title":"Quelle est la position correcte du transpondeur lors du roulage avant décollage ?","options":["A) OFF","B) ALT (Mode C)","C) STBY","D) TEST"],"correct_answers":["C) STBY"]},
    {"id":"aeroschool-theo-006","title":"La phraséologie correcte pour une demande de clairance de roulage doit inclure :","options":["A) Le nombre de passagers et la destination finale","B) Le type d'avion uniquement","C) L'immatriculation, la position et la destination","D) Le niveau de carburant et l'heure estimée de départ"],"correct_answers":["C) L'immatriculation, la position et la destination"]},
    {"id":"aeroschool-theo-007","title":"À partir de quelle altitude AGL le pilote automatique peut-il être engagé selon les SOP standard ?","options":["A) 100 ft AGL","B) 200 ft AGL","C) 400 ft AGL","D) 1000 ft AGL"],"correct_answers":["C) 400 ft AGL"]},
    {"id":"aeroschool-theo-008","title":"Quelle est la séquence correcte après la rotation ?","options":["A) Volets → Train → Puissance réduite","B) Train → Volets selon vitesse (F/S/Green Dot)","C) Volets → Train → PA engagé","D) Train → PA → Volets"],"correct_answers":["B) Train → Volets selon vitesse (F/S/Green Dot)"]},
    {"id":"aeroschool-theo-009","title":"À quelle altitude minimum doit-on rentrer le train d'atterrissage ?","options":["A) Au-dessus de 100 ft AGL","B) Au-dessus de 200 ft AGL","C) Au-dessus de 400 ft AGL","D) Au-dessus de 1000 ft AGL"],"correct_answers":["C) Au-dessus de 400 ft AGL"]},
    {"id":"aeroschool-theo-010","title":"V1 correspond à :","options":["A) La vitesse de rotation","B) La vitesse de décision — au-delà de laquelle l'interruption du décollage n'est plus possible","C) La vitesse de sécurité en montée initiale","D) La vitesse minimale de contrôle au sol"],"correct_answers":["B) La vitesse de décision — au-delà de laquelle l'interruption du décollage n'est plus possible"]},
    {"id":"aeroschool-theo-011","title":"Lors du check-in sur la fréquence départ, que doit annoncer le pilote ?","options":["A) Carburant, destination et niveau requis","B) Immatriculation et type d'appareil uniquement","C) Immatriculation, niveau actuel et route","D) Route et heure estimée d'arrivée"],"correct_answers":["C) Immatriculation, niveau actuel et route"]},
    {"id":"aeroschool-theo-012","title":"Lors d'une SID, le pilote doit :","options":["A) Suivre uniquement les instructions verbales de l'ATC","B) Ignorer les contraintes d'altitude si le PA est engagé","C) Respecter les caps, altitudes et contraintes de vitesse de la procédure","D) Monter directement au niveau de croisière sans contrainte"],"correct_answers":["C) Respecter les caps, altitudes et contraintes de vitesse de la procédure"]},
    {"id":"aeroschool-theo-013","title":"Quelle est la déviation latérale maximale tolérée au décollage ?","options":["A) 2 ft","B) 3 ft","C) 5 ft","D) 10 ft"],"correct_answers":["C) 5 ft"]},
    {"id":"aeroschool-theo-014","title":"En croisière stabilisée, quelle est la tolérance d'altitude acceptable ?","options":["A) ±50 ft","B) ±100 ft","C) ±200 ft","D) ±500 ft"],"correct_answers":["C) ±200 ft"]},
    {"id":"aeroschool-theo-015","title":"En croisière stabilisée, quelle est la tolérance de cap acceptable ?","options":["A) ±2°","B) ±3°","C) ±5°","D) ±10°"],"correct_answers":["C) ±5°"]},
    {"id":"aeroschool-theo-016","title":"Lors d'un passage sur une nouvelle fréquence ATC, le check-in doit inclure :","options":["A) Le type d'aéronef, la vitesse et le carburant restant","B) L'immatriculation, le niveau actuel et la route","C) Le niveau de croisière et l'heure d'arrivée estimée uniquement","D) Le nom du commandant de bord et la destination"],"correct_answers":["B) L'immatriculation, le niveau actuel et la route"]},
    {"id":"aeroschool-theo-017","title":"Qu'est-ce qu'un read-back de clairance ?","options":["A) Une confirmation visuelle sur le ND","B) La lecture silencieuse de la clairance sur le FMC","C) La répétition complète et correcte de la clairance reçue par radio","D) Une annotation dans le journal de bord"],"correct_answers":["C) La répétition complète et correcte de la clairance reçue par radio"]},
    {"id":"aeroschool-theo-018","title":"Lors d'un fuel check en route, que doit faire le pilote si le carburant réel est inférieur au plan de vol ?","options":["A) Continuer normalement, la réserve finale suffit toujours","B) Déclarer immédiatement un MAYDAY","C) Évaluer la nécessité d'un déroutement vers un aéroport de dégagement","D) Réduire la puissance pour économiser le carburant sans en informer l'ATC"],"correct_answers":["C) Évaluer la nécessité d'un déroutement vers un aéroport de dégagement"]},
    {"id":"aeroschool-theo-019","title":"En zone sans radar, quels comptes rendus le pilote doit-il effectuer ?","options":["A) Aucun, le transpondeur suffit","B) Seulement en cas d'urgence","C) Des comptes rendus de position à des points fixes définis","D) Uniquement si demandé par le centre de contrôle"],"correct_answers":["C) Des comptes rendus de position à des points fixes définis"]},
    {"id":"aeroschool-theo-020","title":"Quand doit être obtenu l'ATIS de destination ?","options":["A) Après avoir été mis en descente par l'ATC","B) À l'établissement du premier contact avec l'approche","C) Avant le début de la descente","D) Lors de l'alignement sur le localizer"],"correct_answers":["C) Avant le début de la descente"]},
    {"id":"aeroschool-theo-021","title":"Qu'est-ce que le TOD (Top Of Descent) ?","options":["A) Le point où les volets sont sortis","B) Le point où le train est sorti","C) Le point où la descente doit être initiée pour respecter les contraintes d'arrivée","D) L'altitude minimale de descente"],"correct_answers":["C) Le point où la descente doit être initiée pour respecter les contraintes d'arrivée"]},
    {"id":"aeroschool-theo-022","title":"Quelle est la contrainte de vitesse standard sous FL100 lors d'une STAR ?","options":["A) 200 kts","B) 230 kts","C) 250 kts","D) 280 kts"],"correct_answers":["C) 250 kts"]},
    {"id":"aeroschool-theo-023","title":"Un briefing d'approche doit obligatoirement inclure :","options":["A) Le nom du copilote et la durée du vol","B) La DA/MDA, les fréquences, le cap d'approche et les minima","C) La météo de départ et le carburant chargé","D) Le type d'avion et le nombre de passagers"],"correct_answers":["B) La DA/MDA, les fréquences, le cap d'approche et les minima"]},
    {"id":"aeroschool-theo-024","title":"La tolérance maximale de déviation sur l'axe LOC (localizer) est de :","options":["A) ±2 points","B) ±1 point","C) ±0,5 point","D) ±3 points"],"correct_answers":["B) ±1 point"]},
    {"id":"aeroschool-theo-025","title":"Une approche est considérée stabilisée en IMC à partir de :","options":["A) 500 ft AAL","B) 700 ft AAL","C) 1000 ft AAL","D) 1500 ft AAL"],"correct_answers":["C) 1000 ft AAL"]},
    {"id":"aeroschool-theo-026","title":"Si le pilote n'a pas reçu la clairance d'atterrissage à 500 ft, il doit :","options":["A) Continuer l'approche et demander à nouveau à 200 ft","B) Effectuer un circuit d'attente","C) Effectuer une remise des gaz immédiate","D) Atterrir et avertir la tour après le toucher"],"correct_answers":["C) Effectuer une remise des gaz immédiate"]},
    {"id":"aeroschool-theo-027","title":"Quelle est la tolérance de vitesse au toucher par rapport à Vref ?","options":["A) ±5 kts","B) ±10 kts","C) ±15 kts","D) ±20 kts"],"correct_answers":["B) ±10 kts"]},
    {"id":"aeroschool-theo-028","title":"Quelle valeur de g au toucher est considérée comme un atterrissage dur ?","options":["A) > 1.2 g","B) > 1.5 g","C) > 1.8 g","D) > 2.0 g"],"correct_answers":["C) > 1.8 g"]},
    {"id":"aeroschool-theo-029","title":"Quelle est la zone de toucher cible sur la piste ?","options":["A) Les 500 premiers pieds","B) Les 1000 premiers pieds / 300 premiers mètres","C) Le premier tiers de la piste","D) Le centre géométrique de la piste"],"correct_answers":["B) Les 1000 premiers pieds / 300 premiers mètres"]},
    {"id":"aeroschool-theo-030","title":"Quelle est la vitesse maximale avant d'effectuer un virage lors du dégagement piste ?","options":["A) 20 kts","B) 30 kts","C) 15 kts","D) 10 kts"],"correct_answers":["C) 15 kts"]},
    {"id":"aeroschool-theo-031","title":"Quelle est la tolérance de maintien d'axe lors du freinage après atterrissage ?","options":["A) ±3 ft","B) ±5 ft","C) ±10 ft","D) ±1 ft"],"correct_answers":["A) ±3 ft"]},
    {"id":"aeroschool-theo-032","title":"Que doit annoncer le pilote à la tour après avoir dégagé la piste ?","options":["A) Son temps de vol total","B) Le carburant restant","C) Le dégagement de piste et la demande de roulage vers le parking","D) Le niveau de passagers et de bagages"],"correct_answers":["C) Le dégagement de piste et la demande de roulage vers le parking"]},
    {"id":"aeroschool-theo-033","title":"Un déclenchement GPWS non corrigé en combien de secondes constitue un critère éliminatoire ?","options":["A) 3 secondes","B) 5 secondes","C) 10 secondes","D) 15 secondes"],"correct_answers":["B) 5 secondes"]},
    {"id":"aeroschool-theo-034","title":"Qu'est-ce que le CFIT ?","options":["A) Un type de panne moteur en croisière","B) Une procédure d'approche non précise","C) Un impact avec le terrain sans perte de contrôle préalable — Controlled Flight Into Terrain","D) Une déviation non autorisée de la SID"],"correct_answers":["C) Un impact avec le terrain sans perte de contrôle préalable — Controlled Flight Into Terrain"]},
    {"id":"aeroschool-theo-035","title":"De combien peut-on dépasser VMO/MMO avant que cela constitue un critère éliminatoire ?","options":["A) 5 kts","B) 10 kts","C) 15 kts","D) 20 kts"],"correct_answers":["B) 10 kts"]},
    {"id":"aeroschool-theo-036","title":"Descendre en dessous de la DA/MDA sans référence visuelle acquise est :","options":["A) Autorisé si le pilote automatique est engagé","B) Toléré avec l'accord du copilote","C) Un critère éliminatoire immédiat","D) Acceptable uniquement en VMC"],"correct_answers":["C) Un critère éliminatoire immédiat"]},
    {"id":"aeroschool-theo-037","title":"Le rôle de Pilote Privé (PPL) permet de voler uniquement dans quelles conditions météo ?","options":["A) IMC et VMC","B) IMC uniquement","C) VMC uniquement","D) Toutes conditions avec instructeur à bord"],"correct_answers":["C) VMC uniquement"]},
    {"id":"aeroschool-theo-038","title":"Combien de passagers maximum un pilote privé peut-il transporter selon l'usage de l'avion ?","options":["A) 2 passagers maximum toujours","B) Aucun passager, vol solo uniquement","C) 4, 5 ou plus selon l'avion utilisé","D) 3 passagers maximum en toutes circonstances"],"correct_answers":["C) 4, 5 ou plus selon l'avion utilisé"]},
    {"id":"aeroschool-theo-039","title":"Dans quel espace aérien le Pilote Privé ne peut-il PAS évoluer ?","options":["A) Classe B","B) Classe C","C) Classe A","D) Classe D"],"correct_answers":["C) Classe A"]},
    {"id":"aeroschool-theo-040","title":"Quelle est la durée totale prévue de la formation PPL ?","options":["A) 1h00","B) 2h00","C) 3h00 (pouvant être découpée en plusieurs parties)","D) 5h00"],"correct_answers":["C) 3h00 (pouvant être découpée en plusieurs parties)"]},
    {"id":"aeroschool-theo-041","title":"Quels aéronefs sont approuvés pour la formation PPL ?","options":["A) B737, A320, B777","B) P28A, C172, C182, Piper Cub, C402 et leurs dérivés amphibis","C) Tout aéronef civil homologué","D) Uniquement les monomoteurs à pistons certifiés IFR"],"correct_answers":["B) P28A, C172, C182, Piper Cub, C402 et leurs dérivés amphibis"]},
    {"id":"aeroschool-theo-042","title":"Le rôle de Pilote Privé permet-il de devenir pilote de ligne dans une compagnie ?","options":["A) Oui, avec 100h de vol","B) Oui, si approuvé par l'instructeur","C) Non — il faut poursuivre sur une formation de pilote professionnel","D) Oui, uniquement pour les vols cargo"],"correct_answers":["C) Non — il faut poursuivre sur une formation de pilote professionnel"]},
    {"id":"aeroschool-theo-043","title":"Quelle est la phase de formation abordée en C3 ?","options":["A) Tour de piste et arrondi","B) Navigation et déroutement","C) Relation puissance/vitesse/incidence et décrochage","D) Phraséologies et communication ATC"],"correct_answers":["C) Relation puissance/vitesse/incidence et décrochage"]},
    {"id":"aeroschool-theo-044","title":"Lors de la récupération d'un décrochage, quelle est la procédure correcte ?","options":["A) Tirer sur le manche pour augmenter l'assiette","B) Réduire les gaz et augmenter les volets","C) Pousser le manche pour réduire l'incidence et remettre les gaz","D) Engager le pilote automatique immédiatement"],"correct_answers":["C) Pousser le manche pour réduire l'incidence et remettre les gaz"]},
    {"id":"aeroschool-theo-045","title":"Qu'est-ce qu'un tour de piste ?","options":["A) Un vol de navigation de 30 minutes autour du terrain","B) Un exercice de vol en IMC autour d'un VOR","C) Un circuit visuel standardisé permettant de s'intégrer et d'atterrir sur un terrain","D) Une procédure d'attente IFR en cas de saturation de l'espace"],"correct_answers":["C) Un circuit visuel standardisé permettant de s'intégrer et d'atterrir sur un terrain"]},
    {"id":"aeroschool-theo-046","title":"Qu'est-ce que la phraséologie standard en aviation ?","options":["A) Un langage codé réservé aux contrôleurs","B) Un ensemble de termes libres utilisés selon les situations","C) Un ensemble de formulations normalisées permettant des communications claires et non ambiguës","D) Un système d'abréviations uniquement utilisé en vol IFR"],"correct_answers":["C) Un ensemble de formulations normalisées permettant des communications claires et non ambiguës"]},
    {"id":"aeroschool-theo-047","title":"Lors d'un check-in sur une fréquence ATC, dans quel ordre doit-on se présenter ?","options":["A) Niveau, route, immatriculation","B) Immatriculation, niveau actuel, route ou information reçue","C) Destination, carburant, immatriculation","D) Type d'appareil, vitesse, niveau"],"correct_answers":["B) Immatriculation, niveau actuel, route ou information reçue"]},
    {"id":"aeroschool-theo-048","title":"Qu'est-ce qu'un briefing de départ ?","options":["A) Une réunion entre pilotes avant le vol","B) Une annonce verbale résumant les intentions du pilote avant le décollage, incluant la procédure à suivre en cas de panne","C) Une communication avec l'ATC pour annoncer le départ","D) La lecture de la checklist Before Start"],"correct_answers":["B) Une annonce verbale résumant les intentions du pilote avant le décollage, incluant la procédure à suivre en cas de panne"]},
    {"id":"aeroschool-theo-049","title":"La division de l'attention en cockpit consiste à :","options":["A) Se concentrer uniquement sur les instruments","B) Regarder exclusivement à l'extérieur en VMC","C) Alterner le regard entre les instruments, l'extérieur et la gestion des systèmes de manière équilibrée","D) Déléguer toutes les tâches secondaires au copilote"],"correct_answers":["C) Alterner le regard entre les instruments, l'extérieur et la gestion des systèmes de manière équilibrée"]},
    {"id":"aeroschool-theo-050","title":"Qu'est-ce qu'une clairance ATC ?","options":["A) Une recommandation non contraignante du contrôle","B) Un plan de vol déposé en ligne","C) Une autorisation délivrée par l'ATC permettant à un aéronef d'effectuer une manœuvre spécifique","D) Un code transpondeur assigné par le contrôle"],"correct_answers":["C) Une autorisation délivrée par l'ATC permettant à un aéronef d'effectuer une manœuvre spécifique"]}
  ]$qcm$::jsonb,
  updated_at = now()
WHERE id = 'e1922c0f-7932-45f6-a3b0-f5ac5c9e86d1'::uuid;

-- Vérification (optionnel) : SELECT jsonb_array_length(questions) FROM aeroschool_question_modules WHERE id = 'e1922c0f-7932-45f6-a3b0-f5ac5c9e86d1';
